import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { ArrowLeft, LogOut, Trophy, UserRound } from 'lucide-react';
import { Link } from 'react-router';
import type { User } from 'firebase/auth';

import { Button } from '@/components/ui/Button';
import { usePlayerData } from '@/hooks/usePlayerData';
import {
  ensureAnonymousUser,
  getAuthErrorMessage,
  isExistingCredentialError,
  linkCurrentUserWithGoogle,
  logout,
  signInWithGoogle,
  updateCurrentUserDisplayName
} from '@/services/auth.service';
import { copySoloGamesToUser, refreshUserStats } from '@/services/game.service';
import { getPlayerStats } from '@/services/player-stats.service';
import type { GameDraft } from '@/types/game.types';

type ProfileRouteProps = {
  user: User | null;
};

type ProfileTab = 'player' | 'history';

const placeholderGames: GameDraft[] = [
  {
    id: 'draft_001',
    uid: 'user_001',
    settings: {
      duration: 60,
      allowSkip: true
    },
    answers: [
      {
        word: 'banana',
        syllables: ['ba', 'na', 'na'],
        isCorrect: true,
        isAutoGenerated: false
      },
      {
        word: 'computer',
        syllables: ['com', 'pu', 'ter'],
        isCorrect: true,
        isAutoGenerated: false
      }
    ],
    score: 20,
    accuracy: 100,
    performance: 'excellent',
    startedAtMs: 1717320000000,
    finishedAtMs: 1717320060000
  },
  {
    id: 'draft_002',
    uid: 'user_002',
    settings: {
      duration: 90,
      allowSkip: false
    },
    answers: [
      {
        word: 'elephant',
        syllables: ['el', 'e', 'phant'],
        isCorrect: false,
        isAutoGenerated: false,
        note: 'Expected syllables: el-e-phant'
      },
      {
        word: 'window',
        syllables: ['win', 'dow'],
        isCorrect: true,
        isAutoGenerated: false
      }
    ],
    score: 10,
    accuracy: 50,
    performance: 'average',
    startedAtMs: 1717320100000,
    finishedAtMs: 1717320190000
  },
  {
    id: 'draft_003',
    uid: 'user_003',
    settings: {
      duration: 90,
      allowSkip: true
    },
    answers: [
      {
        word: 'umbrella',
        syllables: ['um', 'brel', 'la'],
        isCorrect: true,
        isAutoGenerated: true
      },
      {
        word: 'guitar',
        syllables: ['gui', 'tar'],
        isCorrect: true,
        isAutoGenerated: false
      },
      {
        word: 'mountain',
        syllables: ['moun', 'tain'],
        isCorrect: true,
        isAutoGenerated: false
      }
    ],
    score: 30,
    accuracy: 100,
    performance: 'excellent',
    startedAtMs: 1717320200000,
    finishedAtMs: 1717320320000
  },
  {
    id: 'draft_004',
    uid: 'user_004',
    settings: {
      duration: 60,
      allowSkip: false
    },
    answers: [],
    score: 0,
    accuracy: 0,
    performance: 'not_started',
    startedAtMs: 1717320400000,
    finishedAtMs: null
  },
  {
    id: 'draft_005',
    uid: 'user_005',
    settings: {
      duration: 90,
      allowSkip: true
    },
    answers: [
      {
        word: 'pencil',
        syllables: ['pen', 'cil'],
        isCorrect: true,
        isAutoGenerated: false
      },
      {
        word: 'tomato',
        syllables: ['to', 'ma', 'to'],
        isCorrect: true,
        isAutoGenerated: true
      },
      {
        word: 'hospital',
        syllables: ['hos', 'pi', 'tal'],
        isCorrect: false,
        isAutoGenerated: false,
        note: 'Incorrect syllable split'
      }
    ],
    score: 20,
    accuracy: 66.67,
    performance: 'good',
    startedAtMs: 1717320500000,
    finishedAtMs: 1717320590000
  },
  {
    id: 'draft_006',
    uid: 'user_006',
    settings: {
      duration: 90,
      allowSkip: false
    },
    answers: [
      {
        word: 'river',
        syllables: ['riv', 'er'],
        isCorrect: false,
        isAutoGenerated: false,
        note: 'Expected syllables: riv-er'
      }
    ],
    score: 0,
    accuracy: 0,
    performance: 'poor',
    startedAtMs: 1717320600000,
    finishedAtMs: 1717320720000
  },
  {
    id: 'draft_007',
    uid: 'user_007',
    settings: {
      duration: 60,
      allowSkip: true
    },
    answers: [
      {
        word: 'butterfly',
        syllables: ['but', 'ter', 'fly'],
        isCorrect: true,
        isAutoGenerated: false
      },
      {
        word: 'rainbow',
        syllables: ['rain', 'bow'],
        isCorrect: true,
        isAutoGenerated: false
      }
    ],
    score: 20,
    accuracy: 100,
    performance: 'excellent',
    startedAtMs: 1717320800000,
    finishedAtMs: 1717320860000
  },
  {
    id: 'draft_008',
    uid: 'user_008',
    settings: {
      duration: 90,
      allowSkip: false
    },
    answers: [
      {
        word: 'calendar',
        syllables: ['cal', 'en', 'dar'],
        isCorrect: true,
        isAutoGenerated: true
      },
      {
        word: 'orange',
        syllables: ['or', 'ange'],
        isCorrect: false,
        isAutoGenerated: false,
        note: 'Incorrect syllable split'
      }
    ],
    score: 10,
    accuracy: 50,
    performance: 'average',
    startedAtMs: 1717320900000,
    finishedAtMs: 1717320990000
  },
  {
    id: 'draft_009',
    uid: 'user_009',
    settings: {
      duration: 90,
      allowSkip: true
    },
    answers: [
      {
        word: 'kangaroo',
        syllables: ['kan', 'ga', 'roo'],
        isCorrect: true,
        isAutoGenerated: false
      },
      {
        word: 'camera',
        syllables: ['cam', 'er', 'a'],
        isCorrect: true,
        isAutoGenerated: false
      },
      {
        word: 'chocolate',
        syllables: ['choc', 'o', 'late'],
        isCorrect: false,
        isAutoGenerated: false,
        note: 'Incorrect syllable split'
      }
    ],
    score: 20,
    accuracy: 66.67,
    performance: 'good',
    startedAtMs: 1717321000000,
    finishedAtMs: 1717321120000
  },
  {
    id: 'draft_010',
    uid: 'user_010',
    settings: {
      duration: 60,
      allowSkip: true
    },
    answers: [],
    score: 0,
    accuracy: 0,
    performance: 'not_started',
    startedAtMs: 1717321200000,
    finishedAtMs: null
  }
];

export function ProfileRoute({ user }: ProfileRouteProps) {
  const playerData = usePlayerData(user);
  const stats = getPlayerStats(playerData.games);
  // const finishedGames = playerData.games.filter(
  //   (game) => game.finishedAtMs !== null
  // );
  const finishedGames = placeholderGames;
  const [displayName, setDisplayName] = useState('');
  const [statusMessage, setStatusMessage] = useState('');
  const [errorMessage, setErrorMessage] = useState('');
  const [pendingAction, setPendingAction] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<ProfileTab>('player');
  const providerIds =
    user?.providerData.map((provider) => provider.providerId) ?? [];
  const hasGoogleProvider = providerIds.includes('google.com');

  useEffect(() => {
    setDisplayName(
      playerData.profile?.displayName ?? user?.displayName ?? 'Pemain Tamu'
    );
  }, [playerData.profile?.displayName, user?.displayName]);

  return (
    <div className="flex min-h-0 flex-1 flex-col">
      <header className="flex min-h-16 items-center gap-3 text-xl font-bold">
        <Link
          aria-label="Kembali"
          className="focus-ring inline-flex h-10 w-10 items-center justify-center"
          to="/"
        >
          <ArrowLeft size={28} />
        </Link>
        <span>Profil</span>
      </header>

      <section className="mt-4 flex min-h-0 flex-1 flex-col">
        <div
          aria-label="Bagian profil"
          className="grid grid-cols-2 gap-2"
          role="tablist"
        >
          <ProfileTabButton
            activeTab={activeTab}
            icon={<UserRound size={18} />}
            label="Kartu Pemain"
            tab="player"
            onSelect={setActiveTab}
          />
          <ProfileTabButton
            activeTab={activeTab}
            icon={<Trophy size={18} />}
            label="Riwayat"
            tab="history"
            onSelect={setActiveTab}
          />
        </div>

        <div
          aria-labelledby={`profile-tab-${activeTab}`}
          className={`panel mt-4 min-h-0 flex-1 bg-white p-4 ${
            activeTab === 'history'
              ? 'flex max-h-[min(34rem,calc(100vh-11rem))] flex-col'
              : 'overflow-y-auto'
          }`}
          id={`profile-panel-${activeTab}`}
          role="tabpanel"
        >
          {activeTab === 'player' ? (
            <>
              <div className="flex items-center gap-3">
                <UserRound size={24} />
                <h1 className="text-sm font-bold">Kartu Pemain</h1>
              </div>
              {playerData.isLoading ? (
                <p className="mt-5 text-xs leading-6 text-zinc-700">
                  Memuat data...
                </p>
              ) : (
                <div className="mt-5 space-y-5">
                  <div>
                    <p className="text-xs leading-6 text-zinc-600">Nama</p>
                    <p className="mt-1 text-sm font-bold">
                      {playerData.profile?.displayName ??
                        user?.displayName ??
                        'Pemain Tamu'}
                    </p>
                    <p className="mt-2 text-[0.65rem] text-[#8f8f17]">
                      {user?.isAnonymous ? 'Tamu' : 'Tersimpan'}
                    </p>
                  </div>
                  <dl className="space-y-3 text-xs leading-6">
                    <StatRow label="Total Main" value={stats.gamesPlayed} />
                    <StatRow
                      label="Total Kata"
                      value={stats.totalCorrectWords}
                    />
                    <StatRow label="Rekor Kata" value={stats.bestStreak} />
                    <StatRow
                      label="Rata-rata Akurasi"
                      value={`${stats.averageAccuracy}%`}
                    />
                  </dl>
                  <AccountControls
                    displayName={displayName}
                    errorMessage={errorMessage}
                    hasGoogleProvider={hasGoogleProvider}
                    onDisplayNameChange={setDisplayName}
                    onGoogleAction={() => void onGoogleAction()}
                    onLogout={() => void onLogout()}
                    onSaveDisplayName={(event) => void onSaveDisplayName(event)}
                    pendingAction={pendingAction}
                    statusMessage={statusMessage}
                    user={user}
                  />
                </div>
              )}
            </>
          ) : (
            <div className="flex min-h-0 flex-1 flex-col">
              <div className="flex items-center gap-3">
                <Trophy size={24} />
                <h2 className="text-sm font-bold">Riwayat Permainan</h2>
              </div>
              {playerData.error && (
                <p className="mt-5 text-xs leading-6 text-[#9a3412]">
                  {playerData.error}
                </p>
              )}
              {!playerData.error && playerData.isLoading && (
                <p className="mt-5 text-xs leading-6 text-zinc-700">
                  Memuat riwayat...
                </p>
              )}
              {!playerData.error && !playerData.isLoading && (
                <GameHistory games={finishedGames} />
              )}
            </div>
          )}
        </div>
      </section>
    </div>
  );

  async function onGoogleAction() {
    if (!user || pendingAction) {
      return;
    }

    const guestGames = user.isAnonymous ? playerData.games : [];
    setPendingAction('google');
    setStatusMessage('');
    setErrorMessage('');

    try {
      if (user.isAnonymous || !hasGoogleProvider) {
        const linkedUser = await linkCurrentUserWithGoogle();
        await refreshUserStats(linkedUser.uid);
        setStatusMessage('Akun Google terhubung.');
        return;
      }

      setStatusMessage('Akun Google sudah terhubung.');
    } catch (error) {
      if (user.isAnonymous && isExistingCredentialError(error)) {
        try {
          const signedInUser = await signInWithGoogle();
          await copySoloGamesToUser(guestGames, signedInUser.uid);
          setStatusMessage('Progres tamu digabungkan ke akun Google.');
          return;
        } catch (signInError) {
          setErrorMessage(getAuthErrorMessage(signInError));
          return;
        }
      }

      setErrorMessage(getAuthErrorMessage(error));
    } finally {
      setPendingAction(null);
    }
  }

  async function onSaveDisplayName(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();

    if (!user || pendingAction) {
      return;
    }

    setPendingAction('name');
    setStatusMessage('');
    setErrorMessage('');

    try {
      await updateCurrentUserDisplayName(displayName);
      setStatusMessage('Nama pemain diperbarui.');
    } catch (error) {
      setErrorMessage(getAuthErrorMessage(error));
    } finally {
      setPendingAction(null);
    }
  }

  async function onLogout() {
    if (pendingAction) {
      return;
    }

    setPendingAction('logout');
    setStatusMessage('');
    setErrorMessage('');

    try {
      await logout();
      await ensureAnonymousUser();
      setStatusMessage('Keluar dari akun tersimpan.');
    } catch (error) {
      setErrorMessage(getAuthErrorMessage(error));
    } finally {
      setPendingAction(null);
    }
  }
}

type ProfileTabButtonProps = {
  activeTab: ProfileTab;
  icon: ReactNode;
  label: string;
  onSelect: (tab: ProfileTab) => void;
  tab: ProfileTab;
};

function ProfileTabButton({
  activeTab,
  icon,
  label,
  onSelect,
  tab
}: ProfileTabButtonProps) {
  const isActive = activeTab === tab;

  return (
    <button
      aria-controls={`profile-panel-${tab}`}
      aria-selected={isActive}
      className={`focus-ring pixel-btn inline-flex min-h-12 items-center justify-center gap-2 px-2 py-3 text-[0.6rem] font-bold leading-5 sm:text-xs ${
        isActive ? '!bg-zinc-950 !text-white !shadow-none' : ''
      }`}
      id={`profile-tab-${tab}`}
      onClick={() => onSelect(tab)}
      role="tab"
      type="button"
    >
      <span className="inline-flex shrink-0">{icon}</span>
      <span>{label}</span>
    </button>
  );
}

type AccountControlsProps = {
  displayName: string;
  errorMessage: string;
  hasGoogleProvider: boolean;
  onDisplayNameChange: (value: string) => void;
  onGoogleAction: () => void;
  onLogout: () => void;
  onSaveDisplayName: (event: FormEvent<HTMLFormElement>) => void;
  pendingAction: string | null;
  statusMessage: string;
  user: User | null;
};

function AccountControls({
  displayName,
  errorMessage,
  hasGoogleProvider,
  onDisplayNameChange,
  onGoogleAction,
  onLogout,
  onSaveDisplayName,
  pendingAction,
  statusMessage,
  user
}: AccountControlsProps) {
  const isAnonymous = user?.isAnonymous ?? true;

  return (
    <section className="border-zinc-950 pt-5">
      <h2 className="text-sm font-bold">
        {isAnonymous ? 'Simpan Progres' : 'Akun Tersimpan'}
      </h2>
      <p className="mt-3 text-[0.6rem] leading-5 text-zinc-600">
        {isAnonymous
          ? 'Hubungkan Google agar riwayat permainan tidak hilang.'
          : 'Progres tersimpan di akun Google ini.'}
      </p>

      <div className="mt-4 space-y-4">
        <Button
          className="w-full text-xs"
          disabled={
            pendingAction !== null || (!isAnonymous && hasGoogleProvider)
          }
          onClick={onGoogleAction}
        >
          {pendingAction === 'google'
            ? 'Menghubungkan...'
            : hasGoogleProvider
              ? 'Google Terhubung'
              : 'Hubungkan Google'}
        </Button>

        {!isAnonymous && (
          <>
            <form className="space-y-3" onSubmit={onSaveDisplayName}>
              <label className="block">
                <span className="text-[0.6rem] leading-5 text-zinc-600">
                  Nama Tampilan
                </span>
                <input
                  autoComplete="nickname"
                  className="focus-ring pixel-box mt-2 w-full bg-white px-3 py-3 text-xs"
                  disabled={pendingAction !== null}
                  onChange={(event) => onDisplayNameChange(event.target.value)}
                  type="text"
                  value={displayName}
                />
              </label>
              <Button
                className="w-full text-xs"
                disabled={pendingAction !== null}
                type="submit"
              >
                {pendingAction === 'name' ? 'Menyimpan...' : 'Simpan Nama'}
              </Button>
            </form>
            <Button
              className="w-full text-xs"
              disabled={pendingAction !== null}
              onClick={onLogout}
              variant="danger"
            >
              <LogOut size={18} />
              {pendingAction === 'logout' ? 'Keluar...' : 'Keluar'}
            </Button>
          </>
        )}
      </div>

      {statusMessage && (
        <p className="mt-4 text-[0.6rem] leading-5 text-[#8f8f17]">
          {statusMessage}
        </p>
      )}
      {errorMessage && (
        <p className="mt-4 border-[3px] border-[#e76e54] bg-white p-3 text-[0.6rem] leading-5 text-[#9a3412]">
          {errorMessage}
        </p>
      )}

      {isAnonymous && (
        <p className="mt-4 text-[0.55rem] leading-5 text-zinc-500">
          Jika akun Google sudah ada, progres tamu akan digabungkan setelah
          masuk.
        </p>
      )}
    </section>
  );
}

type StatRowProps = {
  label: string;
  value: number | string;
};

function StatRow({ label, value }: StatRowProps) {
  return (
    <div className="flex items-center justify-between gap-4 border-b-[3px] border-zinc-950 pb-3">
      <dt>{label}</dt>
      <dd className="font-bold text-[#8f8f17]">{value}</dd>
    </div>
  );
}

type GameHistoryProps = {
  games: GameDraft[];
};

function GameHistory({ games }: GameHistoryProps) {
  if (games.length === 0) {
    return (
      <p className="mt-5 text-xs leading-6 text-zinc-700">
        Belum ada riwayat. Selesaikan permainan untuk mengisi daftar ini.
      </p>
    );
  }

  return (
    <ol className="mt-5 min-h-0 flex-1 space-y-3 overflow-y-auto pr-1">
      {games.map((game) => (
        <li
          className="border-[3px] border-zinc-950 bg-[#dee4e7] p-3"
          key={game.id}
        >
          <p className="text-xs font-bold leading-6">
            {formatGameDate(game.startedAtMs)}
          </p>
          <p className="mt-1 text-[0.6rem] leading-5 text-zinc-600">
            {game.settings.duration} detik
          </p>
          <dl className="mt-3 grid grid-cols-2 gap-2 text-center">
            <div className="border-[3px] border-zinc-950 bg-white px-2 py-2">
              <dt className="text-[0.55rem] leading-4 text-zinc-600">Kata</dt>
              <dd className="mt-1 text-xs font-bold">{game.score}</dd>
            </div>
            <div className="border-[3px] border-zinc-950 bg-white px-2 py-2">
              <dt className="text-[0.55rem] leading-4 text-zinc-600">
                Akurasi
              </dt>
              <dd className="mt-1 text-xs font-bold">
                {formatAccuracy(game.accuracy)}%
              </dd>
            </div>
          </dl>
          <p className="mt-3 text-[0.6rem] leading-5 text-zinc-600">
            Performa:{' '}
            <span className="font-bold text-[#8f8f17]">{game.performance}</span>
          </p>
        </li>
      ))}
    </ol>
  );
}

function formatAccuracy(accuracy: number): string {
  return Number.isInteger(accuracy) ? String(accuracy) : accuracy.toFixed(1);
}

function formatGameDate(timestampMs: number): string {
  return new Intl.DateTimeFormat('id-ID', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  }).format(new Date(timestampMs));
}
