import { afterEach, describe, expect, it } from 'vitest';

import type { GameAnswer, GameDraft } from '@/types/game.types';

import { resetWordsForTest, setWordsForTest } from './word.service';
import { validateAnswer } from './game-rules.service';

const firstAnswer: GameAnswer = {
  word: 'makan',
  syllables: ['ma', 'kan'],
  isCorrect: true,
  isAutoGenerated: true
};

function makeGame(answers: GameAnswer[] = [firstAnswer]): GameDraft {
  return {
    id: 'game-id',
    uid: 'uid',
    settings: { duration: 60, allowSkip: true },
    answers,
    startedAtMs: 0,
    finishedAtMs: null
  };
}

describe('game-rules.service', () => {
  afterEach(() => {
    resetWordsForTest();
  });

  it('rejects a word that does not start with the current last syllable', async () => {
    setWordsForTest(['data']);

    await expect(validateAnswer(makeGame(), 'data')).resolves.toEqual({
      isCorrect: false,
      note: 'kata tidak valid.'
    });
  });

  it('rejects a word that is not in the dictionary', async () => {
    setWordsForTest(['kantor']);

    await expect(validateAnswer(makeGame(), 'kancil')).resolves.toEqual({
      isCorrect: false,
      note: 'kata tidak ditemukan.'
    });
  });

  it('rejects a repeated word', async () => {
    setWordsForTest(['kandidat']);
    const game = makeGame([
      firstAnswer,
      {
        word: 'kandidat',
        syllables: ['kandi', 'dat'],
        isCorrect: false,
        isAutoGenerated: false
      }
    ]);

    await expect(validateAnswer(game, 'kandidat')).resolves.toEqual({
      isCorrect: false,
      note: 'kata sudah pernah dijawab.'
    });
  });

  it('accepts valid answers and skipped words', async () => {
    setWordsForTest(['kandidat']);

    await expect(validateAnswer(makeGame(), 'kandidat')).resolves.toEqual({
      isCorrect: true
    });
    await expect(validateAnswer(makeGame(), 'apa', true)).resolves.toEqual({
      isCorrect: true
    });
  });
});
