import {
  Timestamp,
  doc,
  getDoc,
  onSnapshot,
  setDoc,
  updateDoc,
  type Unsubscribe
} from 'firebase/firestore';

import { getFirebaseServices } from '@/lib/firebase';
import { splitWordByLastSyllable } from '@/lib/syllable';
import type {
  GameAnswer,
  GameDraft,
  GameSettings,
  SoloGame
} from '@/types/game.types';

import { getSoloGameReport } from './report.service';
import { getRandomWord } from './word.service';

export async function createSoloGame(
  uid: string,
  settings: GameSettings
): Promise<string> {
  const { db } = getFirebaseServices();
  const gameRef = doc(db, 'games', crypto.randomUUID());
  const firstWord = await getRandomWord();
  const syllableResult = await splitWordByLastSyllable(firstWord);
  const startedAt = Timestamp.now();

  const firstAnswer: GameAnswer = {
    word: syllableResult.word,
    syllables: syllableResult.parts,
    isCorrect: true,
    isAutoGenerated: true,
    timestamp: startedAt
  };

  const game: SoloGame = {
    id: gameRef.id,
    uid,
    settings,
    answers: [firstAnswer],
    score: 0,
    accuracy: 0,
    performance: 'kurang',
    startedAt,
    finishedAt: null
  };

  await setDoc(gameRef, game);
  return gameRef.id;
}

export function subscribeToSoloGame(
  gameId: string,
  onChange: (game: GameDraft | null) => void,
  onError: (error: Error) => void
): Unsubscribe {
  const { db } = getFirebaseServices();

  return onSnapshot(
    doc(db, 'games', gameId),
    (snapshot) => {
      if (!snapshot.exists()) {
        onChange(null);
        return;
      }

      onChange(toGameDraft(snapshot.data() as SoloGame));
    },
    onError
  );
}

export async function getSoloGame(gameId: string): Promise<GameDraft | null> {
  const { db } = getFirebaseServices();
  const snapshot = await getDoc(doc(db, 'games', gameId));

  if (!snapshot.exists()) {
    return null;
  }

  return toGameDraft(snapshot.data() as SoloGame);
}

export async function appendSoloAnswer(
  game: GameDraft,
  answer: GameAnswer
): Promise<void> {
  const { db } = getFirebaseServices();
  const answers = [...game.answers, { ...answer, timestamp: Timestamp.now() }];
  const report = getSoloGameReport({ ...game, answers });

  await updateDoc(doc(db, 'games', game.id), {
    answers,
    score: report.score,
    accuracy: report.accuracy,
    performance: report.performance,
    updatedAt: Timestamp.now()
  });
}

export async function finishSoloGame(game: GameDraft): Promise<void> {
  if (game.finishedAtMs !== null) {
    return;
  }

  const { db } = getFirebaseServices();
  const report = getSoloGameReport(game);

  await updateDoc(doc(db, 'games', game.id), {
    score: report.score,
    accuracy: report.accuracy,
    performance: report.performance,
    finishedAt: Timestamp.now(),
    updatedAt: Timestamp.now()
  });
}

function toGameDraft(game: SoloGame): GameDraft {
  return {
    id: game.id,
    uid: game.uid,
    settings: game.settings,
    answers: game.answers,
    startedAtMs: game.startedAt.toMillis(),
    finishedAtMs: game.finishedAt?.toMillis() ?? null
  };
}
