import { splitWordByLastSyllable } from '@/lib/syllable';
import type {
  AnswerValidation,
  GameAnswer,
  GameDraft
} from '@/types/game.types';

import { isWordExists } from './word.service';

export function getCurrentGameAnswer(answers: GameAnswer[]): GameAnswer {
  const correctAnswers = answers.filter((answer) => answer.isCorrect);
  const currentAnswer = correctAnswers.at(-1);

  if (!currentAnswer) {
    throw new Error('Permainan belum memiliki kata awal.');
  }

  return currentAnswer;
}

export function getLastSyllableFromAnswer(answer: GameAnswer): string {
  const lastSyllable = answer.syllables.at(-1);

  if (!lastSyllable) {
    throw new Error('Kata tidak memiliki suku kata terakhir.');
  }

  return lastSyllable;
}

export async function createAnswer(
  game: Pick<GameDraft, 'answers'>,
  word: string,
  isFromSkip = false
): Promise<GameAnswer> {
  const normalizedWord = word.toLowerCase().trim();
  const [validation, syllableResult] = await Promise.all([
    validateAnswer(game, normalizedWord, isFromSkip),
    splitWordByLastSyllable(normalizedWord)
  ]);

  return {
    word: syllableResult.word,
    syllables: syllableResult.parts,
    isAutoGenerated: isFromSkip,
    isCorrect: validation.isCorrect,
    ...(validation.isCorrect ? {} : { note: validation.note })
  };
}

export async function validateAnswer(
  game: Pick<GameDraft, 'answers'>,
  word: string,
  isFromSkip = false
): Promise<AnswerValidation> {
  if (isFromSkip) {
    return { isCorrect: true };
  }

  const currentAnswer = getCurrentGameAnswer(game.answers);
  const lastSyllable = getLastSyllableFromAnswer(currentAnswer);

  if (!word.startsWith(lastSyllable)) {
    return { isCorrect: false, note: 'kata tidak valid.' };
  }

  if (!(await isWordExists(word))) {
    return { isCorrect: false, note: 'kata tidak ditemukan.' };
  }

  if (game.answers.some((answer) => answer.word === word)) {
    return { isCorrect: false, note: 'kata sudah pernah dijawab.' };
  }

  return { isCorrect: true };
}
