import type { GameAnswer, GameDraft, SoloGame } from '@/types/game.types';

export function countCorrectAnswers(answers: GameAnswer[]): number {
  return answers.filter((answer) => answer.isCorrect && !answer.isAutoGenerated)
    .length;
}

export function countAnswersAccuracy(answers: GameAnswer[]): number {
  const attempts = answers.filter((answer) => !answer.isAutoGenerated).length;
  const correctAnswers = countCorrectAnswers(answers);

  return Math.round((correctAnswers / attempts) * 100) || 0;
}

export function countAnswersSpeed(
  game: Pick<GameDraft, 'answers' | 'settings'>
): number {
  return countCorrectAnswers(game.answers) / game.settings.duration || 0;
}

export function getPerformance(
  game: Pick<GameDraft, 'answers' | 'settings'>
): string {
  const performance =
    countAnswersSpeed(game) * countAnswersAccuracy(game.answers);

  if (performance <= 20) return 'kurang';
  if (performance <= 50) return 'cukup';
  if (performance <= 70) return 'baik';
  if (performance <= 85) return 'hebat';
  return 'luar biasa';
}

export function getSoloGameScore(answers: GameAnswer[]): number {
  return countCorrectAnswers(answers);
}

export function getSoloGameReport(game: GameDraft | SoloGame): {
  score: number;
  accuracy: number;
  performance: string;
} {
  return {
    score: getSoloGameScore(game.answers),
    accuracy: countAnswersAccuracy(game.answers),
    performance: getPerformance(game)
  };
}
