import { describe, expect, it } from 'vitest';

import type { GameAnswer, GameDraft } from '@/types/game.types';

import {
  countAnswersAccuracy,
  countAnswersSpeed,
  countCorrectAnswers,
  getPerformance
} from './report.service';

const firstAnswer: GameAnswer = {
  word: 'makan',
  syllables: ['ma', 'kan'],
  isCorrect: true,
  isAutoGenerated: true
};

function makeGame(answers: GameAnswer[], duration = 60): GameDraft {
  return {
    id: 'game-id',
    uid: 'uid',
    settings: { duration: duration as 30 | 60 | 90, allowSkip: true },
    answers,
    startedAtMs: 0,
    finishedAtMs: null
  };
}

describe('report.service', () => {
  it('excludes the first generated word and skipped words from correct count', () => {
    const answers: GameAnswer[] = [
      firstAnswer,
      {
        word: 'kandidat',
        syllables: ['kandi', 'dat'],
        isCorrect: true,
        isAutoGenerated: false
      },
      {
        word: 'data',
        syllables: ['da', 'ta'],
        isCorrect: true,
        isAutoGenerated: true
      }
    ];

    expect(countCorrectAnswers(answers)).toBe(1);
  });

  it('counts accuracy using player attempts only', () => {
    const answers: GameAnswer[] = [
      firstAnswer,
      {
        word: 'kandidat',
        syllables: ['kandi', 'dat'],
        isCorrect: true,
        isAutoGenerated: false
      },
      {
        word: 'tari',
        syllables: ['ta', 'ri'],
        isCorrect: false,
        isAutoGenerated: false
      }
    ];

    expect(countAnswersAccuracy(answers)).toBe(50);
  });

  it('returns zero accuracy when there are no player attempts', () => {
    expect(countAnswersAccuracy([firstAnswer])).toBe(0);
  });

  it('keeps legacy speed and performance thresholds', () => {
    const answers: GameAnswer[] = [
      firstAnswer,
      ...Array.from({ length: 48 }, (_, index) => ({
        word: `kata-${index}`,
        syllables: ['ka', `ta-${index}`],
        isCorrect: true,
        isAutoGenerated: false
      }))
    ];
    const game = makeGame(answers);

    expect(countAnswersSpeed(game)).toBe(0.8);
    expect(getPerformance(game)).toBe('hebat');
  });
});
