import { useEffect, useRef } from 'react';
import { Link, useNavigate } from 'react-router';
import { X } from 'lucide-react';

import {
  countAnswersAccuracy,
  countCorrectAnswers,
  getPerformance
} from '@/services/report.service';
import type { GameDraft } from '@/types/game.types';

const FOCUSABLE_SELECTOR = 'a[href], button:not([disabled])';

type GameOverModalProps = {
  game: GameDraft;
};

export function GameOverModal({ game }: GameOverModalProps) {
  const navigate = useNavigate();
  const chain = game.answers.filter((answer) => answer.isCorrect);
  const panelRef = useRef<HTMLDivElement>(null);
  const headingRef = useRef<HTMLHeadingElement>(null);

  useEffect(() => {
    headingRef.current?.focus();
  }, []);

  useEffect(() => {
    function onKeyDown(event: KeyboardEvent) {
      if (event.key === 'Escape') {
        event.preventDefault();
        void navigate('/bermain');
        return;
      }

      if (event.key !== 'Tab' || !panelRef.current) {
        return;
      }

      const focusable = Array.from(
        panelRef.current.querySelectorAll<HTMLElement>(FOCUSABLE_SELECTOR)
      );
      const first = focusable[0];
      const last = focusable.at(-1);

      if (!first || !last) {
        return;
      }

      // Keep Tab inside the dialog; the game behind it is inert but the browser
      // chrome and address bar are still reachable without a wrap.
      if (event.shiftKey && document.activeElement === first) {
        event.preventDefault();
        last.focus();
        return;
      }

      if (!event.shiftKey && document.activeElement === last) {
        event.preventDefault();
        first.focus();
      }
    }

    window.addEventListener('keydown', onKeyDown, true);
    return () => window.removeEventListener('keydown', onKeyDown, true);
  }, [navigate]);

  return (
    <div className="fixed inset-0 z-20 flex items-center justify-center overflow-y-auto bg-text-primary/45 px-5 py-10">
      <div
        aria-labelledby="game-over-title"
        aria-modal="true"
        className="w-full max-w-[390px] rounded-panel border border-border bg-surface p-6 shadow-modal"
        ref={panelRef}
        role="dialog"
      >
        <div className="flex items-start justify-between gap-4">
          <h2
            className="focus-ring text-page-title font-extrabold text-text-primary"
            id="game-over-title"
            ref={headingRef}
            tabIndex={-1}
          >
            Waktu Habis
          </h2>
          <Link
            aria-label="Tutup"
            className="focus-ring inline-flex h-11 w-11 shrink-0 items-center justify-center rounded-full border border-primary-border-soft bg-primary-soft text-primary-strong"
            to="/bermain"
          >
            <X size={22} />
          </Link>
        </div>
        {chain.length > 0 && (
          <ol
            className="mt-5 flex flex-wrap gap-1.5"
            aria-label="Rantai katamu"
          >
            {chain.map((answer, index) => (
              <li
                className={`rounded-full border px-3 py-1 text-xs font-bold leading-5 ${
                  answer.isAutoGenerated
                    ? 'border-border bg-surface-chip text-text-secondary line-through decoration-dashed'
                    : 'border-secondary-border-soft bg-secondary-soft text-text-primary'
                }`}
                key={`${answer.word}-${index}`}
              >
                {answer.word}
                {answer.isAutoGenerated && (
                  <span className="sr-only"> (dilewati)</span>
                )}
              </li>
            ))}
          </ol>
        )}
        <div className="mt-6 space-y-4 text-body-copy text-text-secondary">
          <p>
            Performa permainanmu{' '}
            <strong className="text-primary-strong">
              {getPerformance(game)}
            </strong>
            .
          </p>
          <p>
            Dalam waktu{' '}
            <strong className="text-text-primary">
              {game.settings.duration} detik
            </strong>
            , kamu berhasil menyambungkan{' '}
            <strong className="text-text-primary">
              {countCorrectAnswers(game.answers)} kata
            </strong>{' '}
            dengan{' '}
            <strong className="text-text-primary">
              akurasi {countAnswersAccuracy(game.answers)}%
            </strong>
            .
          </p>
        </div>
        <Link
          className="focus-ring mt-6 inline-flex min-h-12 w-full items-center justify-center rounded-control border border-primary-strong bg-primary px-5 py-3 text-base font-bold leading-5 text-text-primary shadow-warm-sm transition-colors hover:bg-primary-strong hover:text-text-inverse"
          to="/bermain"
        >
          Main Lagi
        </Link>
      </div>
    </div>
  );
}
