import type { GameAnswer } from '@/types/game.types';

/** Chain rows are uniform 16px, so indent budgets can be counted in characters. */
const MAX_HISTORY_ROWS = 3;
const MAX_INDENT_CHARS = 20;

type ChainLink = {
  word: string;
  prefix: string;
  lastSyllable: string;
  isAutoGenerated: boolean;
};

type WordChainProps = {
  answers: GameAnswer[];
};

export function WordChain({ answers }: WordChainProps) {
  const links = answers.filter((answer) => answer.isCorrect).map(toChainLink);
  const current = links.at(-1);

  if (!current) {
    return null;
  }

  const { visible, hiddenCount } = fitHistoryWindow(links.slice(0, -1));

  return (
    <section aria-label="Rantai kata">
      {hiddenCount > 0 && (
        <p className="text-xs font-bold leading-4 text-text-secondary">
          <span aria-hidden="true">⌃ </span>
          {hiddenCount} kata sebelumnya
        </p>
      )}
      {visible.length > 0 && (
        <ol className="chain-history mt-2 space-y-1">
          {visible.map((link, index) => (
            <li
              className="chain-row truncate text-base font-bold leading-6"
              key={`${link.word}-${index}`}
            >
              {/* The spacer carries the real preceding text, so each word lands
                  under the syllable it inherited without measuring anything. */}
              <span aria-hidden="true" className="invisible">
                {visible
                  .slice(0, index)
                  .map((previous) => previous.prefix)
                  .join('')}
              </span>
              <span
                className={
                  link.isAutoGenerated
                    ? 'text-text-secondary line-through decoration-dashed'
                    : 'text-text-primary'
                }
              >
                {link.prefix}
                <span
                  className={link.isAutoGenerated ? '' : 'text-primary-strong'}
                >
                  {link.lastSyllable}
                </span>
              </span>
              {link.isAutoGenerated && (
                <span className="sr-only"> (dilewati)</span>
              )}
            </li>
          ))}
        </ol>
      )}
      <div className="mt-2 pl-4">
        <div
          className="animate-chain-handoff rounded-panel border border-border bg-surface-raised px-4 py-3 shadow-warm-lg"
          key={current.word}
        >
          <h2 className="chain-hero break-words text-game-word font-extrabold leading-tight text-text-primary">
            {current.prefix}
            <span className="rounded-lg bg-accent px-1 text-text-primary">
              {current.lastSyllable}
            </span>
          </h2>
        </div>
      </div>
    </section>
  );
}

function toChainLink(answer: GameAnswer): ChainLink {
  const lastSyllable = answer.syllables.at(-1) ?? answer.word;
  const prefix = answer.syllables.slice(0, -1).join('');

  return {
    word: answer.word,
    prefix,
    lastSyllable,
    isAutoGenerated: answer.isAutoGenerated
  };
}

/**
 * Indents accumulate, so long Indonesian words would push the newest link off
 * the right edge. Drop the oldest rows into the counter until the window fits.
 */
function fitHistoryWindow(history: ChainLink[]): {
  visible: ChainLink[];
  hiddenCount: number;
} {
  let start = Math.max(0, history.length - MAX_HISTORY_ROWS);

  while (start < history.length) {
    const window = history.slice(start);
    const indentChars = window
      .slice(0, -1)
      .reduce((total, link) => total + link.prefix.length, 0);

    if (indentChars <= MAX_INDENT_CHARS) {
      break;
    }

    start += 1;
  }

  return { visible: history.slice(start), hiddenCount: start };
}
