import type { Timestamp } from 'firebase/firestore';

import type { GAME_DURATIONS } from '@/constants/game';

export type GameDuration = (typeof GAME_DURATIONS)[number];

export type GameSettings = {
  duration: GameDuration;
  allowSkip: boolean;
};

export type GameAnswer = {
  word: string;
  syllables: string[];
  isCorrect: boolean;
  isAutoGenerated: boolean;
  note?: string;
  timestamp?: Timestamp;
};

export type SoloGame = {
  id: string;
  uid: string;
  settings: GameSettings;
  answers: GameAnswer[];
  score: number;
  accuracy: number;
  performance: string;
  startedAt: Timestamp;
  finishedAt: Timestamp | null;
};

export type GameDraft = {
  id: string;
  uid: string;
  settings: GameSettings;
  answers: GameAnswer[];
  score: number;
  accuracy: number;
  performance: string;
  startedAtMs: number;
  finishedAtMs: number | null;
};

export type AnswerValidation =
  | { isCorrect: true }
  | { isCorrect: false; note: string };
